[pytest]

# 自动发现的测试目录
testpaths =
    test_api
    test_ui

# 默认显示简短失败信息
addopts = -ra

# 自定义测试标记
markers =
    api: Requests 接口自动化测试
    ui: Playwright UI 自动化测试
    performance: 性能测试相关用例
    smoke: 冒烟测试