[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -s --alluredir=reports/allure-results
markers =
    smoke: 核心冒烟测试
    admin: 后台管理接口测试
    portal: 商城前台接口测试
    auth: 登录和鉴权测试
    product: 商品相关接口测试
    order: 订单相关接口测试