[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -s --browser chromium --alluredir=reports/allure-results

markers =
    smoke: UI 冒烟测试
    login: 登录相关测试
    product: 商品相关测试
    cart: 购物车相关测试
    portal:商城前台 UI 测试
    order: 订单相关 UI 测试
    admin: 后台管理 UI 测试